### ISSUE TITLE
Add an easy way to pass type arguments in Python

### ISSUE THREAD

**Issue by david-christiansen** [GaloisInc/argo#105]
The following steps need to be carried out:
 - [x] Extend the JSON Cryptol AST with type argument passing, either by extending the `call` form or by adding a new one
 - [ ] Extend the Python class `CryptolFunctionHandle` to support an API for type arguments. One way this could look is to map the Cryptol type argument `a` to the Python keyword argument `type_a`, or to just use keyword arguments for type arguments.
 - [ ] Add these to the documentation.

**Comment by david-christiansen** [comment]
GaloisInc/cryptol#949 solves the server-side part of this, and #115 added the protocol documentation.

**Comment by pnwamk** [comment]
The aforementioned pull requests have been merged - I believe this issue is no longer relevant (and if I'm wrong, feel free to reopen =)
