### ISSUE TITLE
Cryptol API: send bitvectors with padding

### ISSUE THREAD

**Issue by david-christiansen** [GaloisInc/argo#108]
Right now, the 16-bit value 3 is sent as simply "3". We should send "0003" to match Cryptol itself.

**Comment by pnwamk** [comment]
See https://github.com/GaloisInc/cryptol/pull/941 for fix.

**Comment by pnwamk** [comment]
Fixed by https://github.com/GaloisInc/argo/pull/111  and tested by https://github.com/GaloisInc/cryptol/pull/941
