### ISSUE TITLE
call :prove or :check

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/argo#121]
It would be nice to use the python interface for CI related things, but I can't figure out how to call the prover. Is this supported?

**Comment by pnwamk** [comment]
Those commands are not currently supported, but there’s no reason we can’t
add them. I’ll make a note.

**Comment by weaversa** [comment]
Also, please add `:safe` to the list.

**Comment by pnwamk** [comment]
Update: some initial work on prover interaction from the python API is here (it was already implemented in the server API but not exposed in the python API):
https://github.com/GaloisInc/argo/tree/cryptol-remote-api-sat
https://github.com/GaloisInc/cryptol/tree/cryptol-remote-api/sat 

`:prove` should be a trivial addition to what `:sat` is already doing.

`:check`, and `:safe` will require just a little more work.

**Comment by atomb** [comment]
Now that GaloisInc/cryptol#1046 is merged, the equivalent of `:prove` and `:sat` are available. There's not yet an equivalent of `:check` or `:safe`, however, so I'll leave this open as a reminder.
