### ISSUE TITLE
missing field in record construction minTCSolver

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/argo#156]
I'm not exactly sure atm how I got this, but it has something to do with the Cryptol Python client's 'call' function. I get an error that follows the trace through the Python client and ends with:

```argo.interaction.ArgoException: Internal error src/CryptolServer.hs (64,19)-(69,19): missing field in record construction minTCSolver```

I think it's possible that the versions of the client and server are out of sync. Though, whatever the cause, I'm letting you know that I was able to hit this error.

**Comment by pnwamk** [comment]
I believe this was addressed and we've updated the build scripts in `cryptol` to error if this happens again: https://github.com/GaloisInc/cryptol/commit/665b1c7b5d9af2968e38acc763d376f056f63bba#diff-e09012a43b70cbe2a0855c46ea8a107a91e603b1d5a489c5e83e21ede4e6c38b

Thanks for the heads up! =)
