### ISSUE TITLE
Unknown State ID Error

### ISSUE THREAD

**Issue by michaelabernardo** [GaloisInc/argo#158]
Hi there! 

I'm running `cryptol-remote-api` in a CI/CD pipeline, and I'm starting to get errors like: 

```
argo_client.interaction.ArgoException: Unknown state ID f65e5d01-94c4-40ce-88c3-e822283a7129
```

I saw there was a change [here](https://github.com/GaloisInc/argo/pull/155) that had to do with State IDs, so I probably just missed something I need to do to account for the change. I think I remember that there is a command to reset the state...can you remind me what that is? 

I'm using your Python client from the `galois-py-toolkit` repository, Python 3.9, and the nightly Docker image of cryptol-remote-api:

```
Using docker image sha256:d8e96fa7330b144a3e8e814f621bd7535b780c8df3b38b2d51ce3f1649a49363 for galoisinc/cryptol-remote-api:nightly
```

I appreciate any tips! Thanks so much for your help!

**Comment by pnwamk** [comment]
Apologies for that mixup - we should have noted this sooner. Those server
backend changes you referred to should be accounted for in the client here:
https://github.com/GaloisInc/cryptol/tree/master/cryptol-remote-api/python

The galois-py-toolkit repo ended up being a short lived experiment and both
python clients now live next to their respective servers. (I’ll update that
repo today to document that).

For the upcoming release of Cryptol we’re planning an accompanying PyPI
package, so tracking where the client source code is shouldn’t be necessary
soon if there’s not an underlying need/desire to do so.


If using the client in the Cryptol repo doesn’t work let me know and we’ll
see what we can do! =)

**Comment by michaelabernardo** [comment]
Ah right I forgot about that! Thank you!! I'll give that a try and let you know if I end up having issues.
