### ISSUE TITLE
Allow Python client to connect to server with self-signed certificate

### ISSUE THREAD

**Issue by atomb** [GaloisInc/argo#168]
Current, when the Python client connects to a `cryptol-remote-api` server with a self-signed certificate, it produces an error such as

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))
```

This is probably the correct default behavior, but having the option to allow self-signed certificates would be useful sometimes.

**Comment by pnwamk** [comment]
Fix is in https://github.com/GaloisInc/cryptol/pull/1203

TL;DR, `cryptol.connect(url=SERVER_URL, verify=False)` to skip verifying SSL certificates, or if using the lower level argo interface directly, pass `verify=False` to the `HttpProcess` constructor.

**Comment by pnwamk** [comment]
The fix has been merged.
