### ISSUE TITLE
Example SAW test from Python fails

### ISSUE THREAD

**Issue by kwf** [GaloisInc/argo#17]
When I try to execute the test `python/saw-test.py`, I see the following:

```
$ python3 saw-test.py 
Traceback (most recent call last):
  File "saw-test.py", line 8, in <module>
    c = saw.connect("cabal new-exec saw-remote-api -- --dynamic4")
  File "/Users/kwf/Work/protocol/python/saw/__init__.py", line 9, in connect
    proc = ac.ServerProcess(command)
  File "/Users/kwf/Work/protocol/python/argo/connection.py", line 31, in __init__
    self.setup()
  File "/Users/kwf/Work/protocol/python/argo/connection.py", line 60, in setup
    raise Exception("Failed to load process, output was `" + out_line + "' but expected PORT then a port.")
Exception: Failed to load process, output was `Resolving dependencies...
' but expected PORT then a port
```

**Comment by david-christiansen** [comment]
This can be worked around by first running `cabal new-build all`. I don't know how to suppress that message, do you?

**Comment by kwf** [comment]
Oh, I see what the issue is now. Could we have the Python be smart enough to invoke `cabal new-build all` first, wait for it to terminate, then invoke the executable?

**Comment by david-christiansen** [comment]
That would be quite easy to do - Python has good libraries for invoking shell commands.

**Comment by david-christiansen** [comment]
I bet we could actually just set the command parameter to `cabal new-build all && cabal new-exec saw-remote-api -- --dynamic4`

**Comment by kwf** [comment]
Looks like we can use `--verbose=0` to suppress all `cabal` output; I'm going to try updating in the Python scripts to see if that is the easiest way to squash this issue.
