### ISSUE TITLE
ModuleNotFoundError for example Cryptol Python tests

### ISSUE THREAD

**Issue by kwf** [GaloisInc/argo#18]
When I try the Cryptol tests in `python/cryptol-api-test.py` and `python/cryptol-tests.py` I get the following error (the same for both files):

```
$ python3 cryptol-api_test.py
Traceback (most recent call last):
  File "cryptol-api_test.py", line 3, in <module>
    from cryptol import CryptolConnection, CryptolContext, cry
  File "/Users/kwf/Work/protocol/python/cryptol/__init__.py", line 7, in <module>
    from . import cryptoltypes
  File "/Users/kwf/Work/protocol/python/cryptol/cryptoltypes.py", line 3, in <module>
    import BitVector
ModuleNotFoundError: No module named 'BitVector'
```

**Comment by david-christiansen** [comment]
This requires the BitVector package to be installed. I just have it on my machine, but it might be better to get something like virtualenv set up.

**Comment by kwf** [comment]
Oh! Without further investigation I guessed it was coming from inside the Cryptol evaluator.
