### ISSUE TITLE
Invalidate SAW server cache due to file modification

### ISSUE THREAD

**Issue by kwf** [GaloisInc/argo#27]
The Cryptol server uses the `validateServerState` command to invalidate server states when a file changes on disk: https://github.com/GaloisInc/argo/blob/7cb77e1db2b67d5d783cf6def4eb6f9f0242310e/cryptol-remote-api/src/CryptolServer.hs#L73-L83 We should do this with the SAW server too, for LLVM modules, and anything else that touches the disk. This may require altering the set of things that is stored in the server state.

**Comment by david-christiansen** [comment]
I recall @kwf saying they'd do this one - if I remembered wrong, please say so!

**Comment by kwf** [comment]
@david-christiansen Yup, this one is me!
