### ISSUE TITLE
Proof dashboard API

### ISSUE THREAD

**Issue by kwf** [GaloisInc/argo#28]
Use a logging framework or an HTML generation scheme (or both) to produce a nice report from a proof script of the things that were verified. Python reflection will let us grab the names of spec classes, etc.

**Comment by david-christiansen** [comment]
This seems to presently be more working than this ticket specifies. In particular, we have a dynamically-generated dashboard!

As part of the dashboard work, I'd like to see if we can factor it out into an independent library that anyone could have developed, in principle. This will help us maintain it, and it will also expose which primitives are necessary as part of the public SAW Python API for third-party extension.

**Comment by david-christiansen** [comment]
I imagine we can get by with something like the hook mechanism in Emacs, where libraries can register callbacks that are triggered on certain events in the library, or alternatively we can use the standard Python logging interface as it says above.

**Comment by kwf** [comment]
This is a larger ongoing piece of work which will acquire its own more specific tickets—one single tracking ticket isn't useful at this point, so we're closing this issue and creating issues for the more specific technical work.
