### ISSUE TITLE
Document JSONRPC error codes

### ISSUE THREAD

**Issue by david-christiansen** [GaloisInc/argo#3]
We should have a list of all the error codes that might be returned, and a summary of what they mean.

**Comment by kwf** [comment]
If these have stabilized enough to be worth documenting I'm happy to self-assign and go through what's there to produce a document.

**Comment by kwf** [comment]
Here are the error codes I've found digging through the source code:

- The JSON-RPC spec reserves:
  + `-32602`: "Invalid params" (for this particular known method)
  + `-32700`: "Parse error" (i.e. invalid JSON)
  + `-32601`: "Method not found"
  + `-32600`: "Invalid request"
  + `-32603`: "Internal error"
- Our history wrapper cache defines:
  + `32000`: "Missing state field" `Argo.HistoryWrapper` (should this be a sub-error of the JSON-RPC spec's "Invalid request" (`-32600`)?)
- The SAW server defines:
  + `1001`: "No server value with name _____"
  + `1002`: "The server value with name _____ is not a Cryptol environment"
  + `1003`: "The server value with name _____ is not an LLVM module"
  + `1003` **(duplicate!)**: "Not currently setting up Cryptol"
  + `1004`: "The server value with name _____ is not an LLVM setup script"
  + `1004` **(duplicate!)**: "Not currently setting up Crucible/LLVM"
  + `1005`: "Not at top level"
  + `5000`: "Can't load LLVM module"
  + `5001`: [generic Cryptol error with custom content]
  + `6000`: "Verification exception" (with attached exception)
  + `100000`: "Generic error" (TODO note says should be deprecated)
- The Cryptol server defines:
  + `4`: "There was a Cryptol parse error"
  + `45`: "Can't evaluate at polymorphic type" (with type payload as JSON object)
  + `55`: "Prover error" (with error as JSON object)
  + For expressions:
    * `32`: "Invalid Base64" (with `show` of invalid data)
    * `33`: "Not a hex digit" (with `show` of invalid digit)
    * `34`: "Can't convert Cryptol data from this type to JSON" (with `show` of type)
    * `35`: "Execution would have required these defaults" (with `show` of the defaults as a list of parameter/type pairs)
    * `36`: "Can't evaluate Cryptol in a parameterized module" (with JSON list of `pretty` module names)
  + `20000 - 21000` reserved for Cryptol errors made by the `cryptolError` function. Many of these errors coming from the Cryptol evaluator have rich information which could be represented as structured JSON; currently many merely `pretty` that information and attach it as a JSON string or list of strings. The errors here correspond to the constructors of the `ModuleError` type in the Cryptol compiler. Parenthesized are the returned fields in the error details (which will always be a JSON object). Occasionally there will be an extra `path: String` field, as Cryptol will sometimes add an `ErrorInFile` constructor to its internal exceptions, which translates in the output encoding to the addition of a `path` field. Those marked below with a `path` field will always have one; all others *could* but might not.
    * `20000`: "Module not found" (`source: String`, `path: String`)
    * `20001`: "Can't find file" (`path: String`)
    * `20002`: "Bad UTF-8" (`path: String`, `error: String`)
    * `20003`: "Other IO error" (`path: String`, `error: String`)
    * `20004`: "Module parse error" (`source: String`, `error: String`)
    * `20005`: "Recursive modules" (`modules: [String]`)
    * `20006`: "Renamer error(s)" (`source: String`, `errors: [String]`)
    * `20007`: "No pat errors" (`source: String`, `errors: [String]`)
    * `20008`: "No include errors" (`source: String`, `errors: [String]`)
    * `20009`: "Typechecking failed" (`source: String`, `errors: [String]`)
    * `20010`: "Module name mismatch" (`expected: String`, `found: String`)
    * `20011`: "Duplicate module name" (`name: String`, `paths: [String, String]` (2-element list))
    * `20012`: "Other failure" (`error: String`)
    * `20013`: "Imported parameterized module" (`module: String`)
    * `20014`: "Failed to parameterize module defs" (`module: String`, `parameters: [String]`)
    * `20015`: "Not a parameterized module"  (`module: String`)

**Comment by kwf** [comment]
What do you think about this proposal for a new error organization and `data` field information?

The JSON-RPC spec reserved codes must remain the same:
  + `-32602`: "Invalid params" (for this particular known method)
  + `-32700`: "Parse error" (i.e. invalid JSON)
  + `-32601`: "Method not found"
  + `-32600`: "Invalid request"
  + `-32603`: "Internal error"

Our history wrapper cache should throw the JSON-RPC spec's "Invalid request" `-32600` when given a request with a bad state, and attach a `String` payload that states "Missing state parameter".

For all of our custom application-specific errors, I think we should standardize the format for the error data object returned when errors contain a `data` field. I propose that in all cases it *must* be a JSON dict, if it is present (though its presence is, per the JSON-RPC spec, optional). In the cases where it is present, it may or may not contain a `path` field, which references a specific file to which the error pertains. Specific errors are free to define all other fields to hold data of their choice specific to the error at hand.

## SAW Server (`1000`–`1099`)

The SAW server should define errors starting from `1000`–`1099`, but should use the same errors as the Cryptol server for Cryptol errors (that is, when a Cryptol error occurs it should be directly returned as such, which will have a code outside this range).

### Server value errors (`1000`–`1009`)

  * `1000`: "No server value with name _____" `{ name: String }`
  * `1001`: "The server value with name _____ is not a Cryptol environment" `{ name: String }`
  * `1002`: "The server value with name _____ is not an LLVM module" `{ name: String }`
  * `1003`: "The server value with name _____ is not an LLVM setup script" `{ name: String }`
  * `1004`–`1009`: currently unused but reserved

### Setup errors (`1010`–`1019`)

  * `1010`: "Not currently setting up Cryptol"
  * `1011`: "Not currently setting up Crucible/LLVM"
  * `1012`: "Not at top level" (Note: what should be attached here?)
  * `1013`–`1019`: currently unused but reserved

### Loading and filesystem errors (`1020`–`1029`)

  *  `1020`: "Can't load LLVM module" `{ error: String }`
  * `1021`–`1029`: currently unused but reserved

### Verification errors (`1030`–`1099`)

  * `1030`: Verification error `{ error: String }`. Plan to split this into range of errors in future.
  * `1031`–`1099`: currently unused but reserved

## Cryptol Server (`2000`–`2099`)

### Parse, print, and load errors (`2000`–`2019`)

  * `2000`: "There was a Cryptol parse error" `{ error: String, input: String }` (the input is rendered as literal string)
  * `2001`: "Bad UTF-8" `{ path: String, error: String }`
  * `2002`: "Invalid Base64" `{ input: String }`
  * `2003`: "Not a hex digit" `{ input: String }`
  * `2004`: "Can't convert Cryptol data from this type to JSON" (with `{ type: <some JSON> }`, including its pretty representation, as used when sending types in non-erroneous situations)
  * `2005`: "Can't find file" `{ path: String }`
  * `2006`: "Other IO error" `{ path: String, error: String }`
  * `2007`–`2019`: currently unused but reserved

### Evaluation errors (`2020`–`2049`)

  * `2020`: "Can't evaluate at polymorphic type" `{ type: <some JSON> }` (represented identically to how it's rendered in non-erroneous situations)
  * `2021`: "Execution would have required these defaults" `{ defaults: [ { parameter: String, type: <JSON> } ] }`, with type rendered as per usual with pretty and structured representation)
  * `2022`: "Can't evaluate Cryptol in a parameterized module" `{ modules: [String] }`
  * `2023`: "Prover error" `{ error: String }`
  * `2024`–`2049`: currently unused but reserved

### Module errors (`2050`–`2069`)

  * `2050`: "Module not found" `{ source: String, path: String }`
  * `2054`: "Module parse error" `{ source: String, error: String }`
  * `2055`: "Recursive modules" `{ modules: [String] }`
  * `2060`: "Module name mismatch" `{ expected: String, found: String }`
  * `2061`: "Duplicate module name" `{ name: String, paths: [String, String] (2-element list) }`
  * `2063`: "Imported parameterized module" `{ module: String }`
  * `2064`: "Failed to parameterize module defs" `{ module: String, parameters: [String] }`
  * `2065`: "Not a parameterized module"  `{ module: String }`
  * `2066`–`2069`: currently unused but reserved

### Type errors (`2070`–`2099`)

  * `2070`: "Renamer error(s)" `{ source: String, errors: [String] }`
  * `2071`: "No pat errors" `{ source: String, errors: [String] }`
  * `2072`: "No include errors" `{ source: String, errors: [String] }`
  * `2073`: "Typechecking failed" `{ source: String, errors: [String] }` (could be split in future into many separate errors)
  * `2074`–`2098`: currently unused but reserved
  * `2099`: "Other failure" `{ error: String }`

**Comment by david-christiansen** [comment]
I generally like this setup. A couple of quibbles:

1. It seems that there's not a lot of room to expand. Why not give each application a 10000-wide block instead of a 1000-wide block? This way, we avoid having to reallocate the blocks later.

2. Should we distinguish between "missing state" and "bad state"? Also, I don't think that -32600 is suitable for application-level concerns. Based on the JSON RPC spec, it sounds more like it's for situations that e.g. lack a "params" field.

**Comment by kwf** [comment]
> Why not give each application a 10000-wide block instead of a 1000-wide block? This way, we avoid having to reallocate the blocks later.

Sounds good to me. How about I just multiply every number in the above by 10? That means everything will be sparse, so that if there are errors that should be "close" to another existing error we can put them there.

> Should we distinguish between "missing state" and "bad state"?

For the person debugging their client, this is helpful information (and could be distinguished via error message) but I don't know whether the *user* of the client has any need to know about the distinction, since such an error should be some kind of panic—indicating either that the server has returned invalid state or that the client has mangled it before re-sending it. So I don't have strong feelings about whether these deserve to have separate error codes.

> I don't think that -32600 is suitable for application-level concerns. Based on the JSON RPC spec, it sounds more like it's for situations that e.g. lack a "params" field.

I suppose that's true—from close reading of the spec, it seems that -32600 is for things that aren't a valid request from the perspective of JSON-RPC as a *transport layer*, and given our caching protocol exists one level above, I think I now agree this is inappropriate. Perhaps we should reserve a block for Argo-specific errors (proposal: 0-9999?) and place this within it.

**Comment by david-christiansen** [comment]
> Sounds good to me. How about I just multiply every number in the above by 10?

Great!

RE missing state/bad state: I think it's better to separate these. Both indicate a bug in the client, and shouldn't ever be presented to a user, so I think it's better to maximize the debugging capability.

> Perhaps we should reserve a block for Argo-specific errors (proposal: 0-9999?) and place this within it.

Agree on both points.

**Comment by kwf** [comment]
I've edited the comment above to reflect these changes.

**Comment by david-christiansen** [comment]
LGTM :-)

**Comment by kwf** [comment]
Todo on this ticket:
- [ ] fix error codes in `argo`
- [ ] fix error codes in `cryptol-remote-api`
- [ ] fix error codes in `saw-remote-api` (requires `cryptol-remote-api` dependency)
- [ ] document error codes by copying above specification to official docs
- [ ] document which API functions can throw which errors
- [ ] unit tests exercising the various error codes and their contents

**Comment by kwf** [comment]
I've migrated the evolving spec and progress-tracking to the tracking PR: https://github.com/GaloisInc/argo/pull/21. Let's have further discussion there.

**Comment by kwf** [comment]
Fixed by #21.
