### ISSUE TITLE
Port proofs as examples for SAW API

### ISSUE THREAD

**Issue by kwf** [GaloisInc/argo#34]
- [x] Salsa20 (in progress, @atomb working on, @david-christiansen working on re-implementation in higher-level more idiomatic style)
- [ ] SAW intro materials
- [x] Use an assumed spec in a proof
- [ ] FFS + other tutorial examples - requires an extraction method (longer term goal)
- [ ] ?

Make sure they end up in the test suite.

**Comment by david-christiansen** [comment]
@atomb suggested we think about the libsignal Curve 25519 implementation (it exists partially in SAWScript, and does some interesting things).

**Comment by atomb** [comment]
I think the latest stuff in `saw-demos` is probably sufficient for this.
