### ISSUE TITLE
cmd line options

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/argo#47]
What are the differences between dynamic, dynamic4, and socket?

**Comment by david-christiansen** [comment]
The server can speak its protocol over either stdio or a socket. These flags control the socket mode:
 * `--socket PORT` means to run it over a socket on the client-chosen port `PORT`. 
 * `--dynamic` means that the server should listen on an arbitrarily-chosen port on IPv6, and then dump it to stdout so the client can know what to connect to.
 * `--dynamic4` is the same as `--dynamic`, but IPv4.

**Comment by david-christiansen** [comment]
As an update to this, recent versions have a `--help` flag that explains the command line syntax better than the old one did.
