### ISSUE TITLE
Protocol.rst replies

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/argo#50]
Protocol.rst claims: " In particular, replies are always a JSON object with two fields". Here the claim is that the server will always reply with {answer: ..., state: ...} This is not the case. When a module is loaded, the reply does include a state, but inside a "reply" field. An expression evaluation does not respond with a state at all.

**Comment by david-christiansen** [comment]
I think that this is a case of the docs assuming too much context with JSON-RPC, and also not distinguishing between state-mutating commands and pure queries. I'll update them to reflect reality. Thanks!

**Comment by david-christiansen** [comment]
Does this update clarify the situation for you? If not, I'm happy to address it again.

**Comment by weaversa** [comment]
Yes, that seems clear now. Thank you!

**Comment by david-christiansen** [comment]
You're welcome! Thanks for pointing it out!
