### ISSUE TITLE
Initial state field: null?

### ISSUE THREAD

**Issue by david-christiansen** [GaloisInc/argo#54]
We have a bit of an incongruity in our protocol.

On the one hand, we say that the concrete structure of the `state` fields is intended to be abstract, and that clients should not construct them themselves. On the other hand, the initial state is clearly an array `[]`, and the subsequent states sure look like the kind of thing a user might build.

I propose that we replace the initial state with the JSON null value instead. We could additionally encode states through a `Binary` instance and base64 them on the wire to make it clear to users that they are an implementation detail that is subject to change.

**Comment by weaversa** [comment]
I'm in support of changing the empty state to JSON null.

I've wondered if the state variable, if left verbatim, or even base64 encoded, could grow large enough to cause a network performance impact. Imagine creating a lengthy `let` binding, and seeing that go back and forth over the wire. I suggest the state be a constant-sized hash of the state maintained by the server. The client can thus roll back to previous states and also share states. Are there other features the client would want to do with a state object?

**Comment by david-christiansen** [comment]
I think there's one thing the client might want to do with the state that would be ruled out by the constant-size hash implementation: the client may want to migrate their state across server processes. For instance, someone might want to work with a local and a remote server, failing over to the local server when the remote one is not available.

OTOH, this use case might be marginal.
