### ISSUE TITLE
"Unable to find the prelude" when evaluating vector

### ISSUE THREAD

**Issue by kwf** [GaloisInc/argo#6]
In the Cryptol REPL, this interaction works:

```
Cryptol> [1, 2, 3]
Showing a specific instance of polymorphic result:
  * Using 'Integer' for type argument 'rep' of 'Cryptol::demote'
[1, 2, 3]
```

However, when I invoke the `evaluate expression` RPC method with the same input, it makes Cryptol panic:

```
cryptol-remote-api: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/GaloisInc/cryptol/issues

%< ---------------------------------------------------
  Revision:  139c7d50ac878edc8b7bda6512bb6d11fd008624
  Branch:    HEAD
  Location:  Cryptol.ModuleSystem.Base.getPrimMap
  Message:   Unable to find the prelude
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-2.6.1-72fJOHxD99kDyHhCzubAfy:Cryptol.Utils.Panic
  panic, called at src/Cryptol/ModuleSystem/Base.hs:358:19 in cryptol-2.6.1-72fJOHxD99kDyHhCzubAfy:Cryptol.ModuleSystem.Base
%< ---------------------------------------------------
```

The sequence of RPC calls to reproduce:

```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "load module",
  "params": {"file": "/Users/kwf/work/protocol/python/Foo.cry"}
}
```

This file `Foo.cry` is the one checked into the repo at https://github.com/GaloisInc/argo/blob/68c0d7efff903824bcef2a832cb2082a0e9dfd40/python/Foo.cry.

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "evaluate expression",
  "params": {"expression": "[1, 2, 3]"}
}
```

**Aside**: This does not crash the server, it just causes it to never respond to the request, which will hang the client. That is, exceptions like this are not being caught and transmitted as generic errors back to the client—should they be?

**Comment by atomb** [comment]
The Cryptol REPL links in a copy of the [prelude](https://github.com/GaloisInc/cryptol/blob/master/lib/Cryptol.cry) into the binary and makes it available in the environment. I think some of the relevant code for how it does that should be somewhere [here](https://github.com/GaloisInc/cryptol/tree/master/cryptol).

**Comment by kwf** [comment]
I'm assigning to myself because I think this may be (partially) an artifact of something going wrong in my Java codebase. I'll update this ticket when I diagnose—right now, it looks like I'm not consistently sending the state back with every call.

**Comment by david-christiansen** [comment]
>  it looks like I'm not consistently sending the state back with every call.

Right now, the server loads the Prelude when some other module is loaded. This should probably change.

Based on the interaction above, it looks like you're running into what happens when an expression is evaluated without having loaded anything, because the state isn't being sent back.

So I see two things to fix here:
 - There should be an exception handler that sends an error back over JSONRPC
 - The server should have the prelude in scope by default

**Comment by kwf** [comment]
Revisiting: this error was triggered as a result of a failure to propagate state in the Java codebase, which has been fixed.
