### ISSUE TITLE
How to reuse a result with `expression`?

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/argo#68]
The documentation implies that `call` is being deprecated. If so, how can one reuse a prior result (ex, from an `{answer:  { value: ... }}`) in an `expression`? I have two thoughts, the first involves consuming the `value` json and regurgitating it as a Cryptol formatted ascii string (I'd rather not). The second involves using `let` statements. However, with the `call` function, it is easy to add a prior result as an `argument`.

**Comment by david-christiansen** [comment]
The `evaluate expression` method supports more than just strings - it supports any of the constructors of the JSON encoding of Cryptol syntax. In particular, the function application expression `call` should permit this transformation:
```
{"method": "call", "params": {"function": "f", "arguments":[v, ...]}}
```
 into
```
{"method": "evaluate expression", "params": {"expression": "call", "function": "f", "arguments":[v, ...]}}
```
So I think the documentation should be made more explicit here.

**Comment by weaversa** [comment]
Thank you. I see now that `call` is also a submethod of `expression`. I thought `call` was being deprecated all together. Since it is essentially moved under `expression`, I am fine. Thanks!
