### ISSUE TITLE
Python to remote server

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/argo#86]
The `cryptol-remote-api` server can run over a publicly available socket. The Python test cases show how to start and connect to `cryptol-remote-api` locally. How does one use the Python client to connect to `cryptol-remote-api` running on a remote server?

**Comment by david-christiansen** [comment]
This should be working now. Please see https://github.com/GaloisInc/argo/blob/b4d07c1f0f371e4383932d4c10dbba29c31e20e9/cryptol-remote-api/test-scripts/cryptol-tests.py#L170-L173 for an example.

I'm happy to help diagnose if that's not sufficient!

**Comment by weaversa** [comment]
I tested it today and it works. Thank you!
